### ISSUE TITLE
Crash with IC2C 1.5.7

### ISSUE THREAD

**Issue by kappa-maintainer** [e99999/GT-Classic#162]
Crash report:
```---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 3/30/23 8:00 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GregTech Classic (gtclassic)
Caused by: java.lang.NoSuchMethodError: gtclassic.api.block.GTBlockBaseMachine.setUnlocalizedName(Lic2/core/platform/lang/components/base/LocaleComp;)Lnet/minecraft/block/Block;
	at gtclassic.api.block.GTBlockBaseMachine.<init>(GTBlockBaseMachine.java:38)
	at gtclassic.common.block.GTBlockMachine.<init>(GTBlockMachine.java:78)
	at gtclassic.common.block.GTBlockMachine.<init>(GTBlockMachine.java:74)
	at gtclassic.common.GTBlocks.<clinit>(GTBlocks.java:114)
	at gtclassic.GTMod.preInit(GTMod.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 6.1.0-7-amd64
	Java Version: 1.8.0_362, Debian
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Debian
	Memory: 3794370792 bytes (3618 MB) / 4116185088 bytes (3925 MB) up to 4116185088 bytes (3925 MB)
	JVM Flags: 2 total; -Xms4096m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version      | Source                                  | Signature                                |
	|:----- |:----------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2       | minecraft.jar                           | None                                     |
	| LCH   | mcp               | 9.42         | minecraft.jar                           | None                                     |
	| LCH   | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2860-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge             | 14.23.5.2860 | forge-1.12.2-14.23.5.2860-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | ic2               | 2.8.1001     | IC2Classic-1.12-1.5.7.jar               | None                                     |
	| LCH   | ic2-classic-spmod | 0.0.0.0      | IC2Classic-1.12-1.5.7.jar               | None                                     |
	| LCE   | gtclassic         | 1.1.7        | GTClassic-1.1.7.jar                     | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.6 (Compatibility Profile) Mesa 22.3.6' Renderer: 'Mesa Intel(R) HD Graphics 630 (KBL GT2)'```

**Comment by kappa-maintainer** [comment]
https://www.curseforge.com/minecraft/mc-mods/vintage-gregtech
